import Head from "next/head";
import Navbar from "./elements/navbar";

export default function Layout(props) {
	return (
		<>
			<Head>
				<title>Gym Membership</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/" />
			</Head>
			{props.children}
			<Navbar />
		</>
	);
}
