import Head from "next/head";
import Image from "next/image";
import Layout from "../components/Layout";
import styles from "../styles/Home.module.css";

export default function Home() {
	return (
		<Layout>
			<div className={styles.container}>
				<Head>
					<title>Gym Membership</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/" />
				</Head>

				<main className={styles.main}>
					<p className={styles.description}>
						Hello, John Doe
					</p>
					<h4 className={styles.description}><strong>Your Classes</strong></h4>

					<div className={styles.grid}>
						<Image src="/gym/classes.png" width={320} height={153} />

						<div>
							<h3>Latest Newstlatter</h3>
							<Image
								src="/gym/newsletter coaching.png"
								width={320}
								height={153}
							/>
						</div>

						<div>
							<h2> </h2>
							<Image src="/gym/health tips.png" width={320} height={153} />
						</div>

						<div>
							<h2> </h2>
							<Image src="/gym/images.jpg" width={320} height={153} />
						</div>
					</div>
				</main>
			</div>
		</Layout>
	);
}
