import Head from "next/head";
import Image from "next/image";
import Layout from "../components/Layout";
import HomeClassesItem from "../components/elements/HomeClassesItem";
import NewsletterItem from "../components/elements/NewsletterItem";
import "react-responsive-carousel/lib/styles/carousel.min.css";
import { Carousel } from 'react-responsive-carousel';


export default function Home() {
	return (
		<Layout>
			<div className="container p-4">
				<Head>
					<title>Gym Membership</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/" />
				</Head>

				<main className="d-flex flex-column justify-content-center">
					<h4 className="text-start mb-4">Hello, John Doe</h4>
					<h5 className="fw-bolder">Your Classes</h5>

					<Carousel>
					<div className="d-flex ">
						<HomeClassesItem />
						<HomeClassesItem />
						<HomeClassesItem />
					</div>
					<div className="d-flex ">
						<HomeClassesItem />
						<HomeClassesItem />
						<HomeClassesItem />
					</div>
						
					
					</Carousel>

					<h5 className="fw-bolder">Latest Newsletter</h5>
					<div className="d-flex mb-3" >
						<NewsletterItem />
					</div>
					<div className="d-flex mb-3">
						<NewsletterItem />
					</div>
					<div className="d-flex mb-3 ">
						<NewsletterItem />
					</div>
					<div className="d-flex mb-3">
						<NewsletterItem />
					</div>
				</main>
			</div>
		</Layout>
	);
}
